language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then prefer_source="--prefer-source"; else prefer_source=""; fi
    - (which pear && pear install pear/PHP_ParserGenerator-alpha) || pyrus install pear/PHP_ParserGenerator-alpha
    - phpenv rehash
    - cp data/Parser.y src/Erebot/Module/Countdown/Parser.y
    - (which pear && PHP_PEAR_INSTALL_DIR="`pear config-get php_dir`" phplemon -q -s src/Erebot/Module/Countdown/Parser.y) || PHP_PEAR_INSTALL_DIR="`pyrus get php_dir | tail -n 1`" phplemon -q -s src/Erebot/Module/Countdown/Parser.y
    - composer self-update -n
    - composer install --dev -n $prefer_source

script:
    - phpunit --coverage-clover clover.xml --bootstrap vendor/erebot/testenv/bootstrap.php tests/

after_script:
    - composer require --dev $prefer_source "satooshi/php-coveralls dev-master"
    - php vendor/bin/coveralls -n -v

